import { useState } from 'react';
import type { HumanProposal, IdeaSupport } from '../../../types/idea';
import { label } from './ReviewSetup';
export function RevisionPlan({ proposals, onChange, disabled, manualSupport, manualChapter }: { proposals: HumanProposal[]; onChange: (v: HumanProposal[]) => void; disabled: boolean; manualSupport?: IdeaSupport; manualChapter?: string }) {
  const [change, setChange] = useState(''), [rationale, setRationale] = useState('');
  return <fieldset disabled={disabled}><legend>Faculty revision plan</legend><p>Accepting a suggestion records a plan; it does not edit or publish a source.</p>{!proposals.length && <p>No proposals added yet.</p>}<label>New faculty proposal<textarea maxLength={4000} value={change} onChange={(e) => setChange(e.target.value)} /></label><label>Rationale for new proposal<textarea maxLength={4000} value={rationale} onChange={(e) => setRationale(e.target.value)} /></label><button disabled={!manualSupport || !change.trim() || !rationale.trim() || proposals.length >= 100} onClick={() => { onChange([...proposals, { id: crypto.randomUUID(), originRunID: null, chapter: manualChapter || 'Captured chapter', change, rationale, support: manualSupport!, destination: 'instructor_supplement', priority: 'medium', disposition: 'proposed' }]); setChange(''); setRationale(''); }}>Add faculty proposal to plan</button>{proposals.map((p) => {
    const update = (patch: Partial<HumanProposal>) => onChange(proposals.map((v) => v.id === p.id ? { ...v, ...patch } : v));
    return <fieldset key={p.id}><legend>{p.chapter}</legend><p>{p.originRunID ? 'Adapted from an AI draft' : 'Faculty proposal'}</p><label>Planned change<textarea maxLength={4000} value={p.change} onChange={(e) => update({ change: e.target.value })} /></label><label>Rationale<textarea maxLength={4000} value={p.rationale} onChange={(e) => update({ rationale: e.target.value })} /></label>
      <label>Disposition<select value={p.disposition} onChange={(e) => update({ disposition: e.target.value as HumanProposal['disposition'] })}>{['proposed', 'accepted_for_plan', 'rejected', 'deferred'].map((v) => <option key={v} value={v}>{label(v)}</option>)}</select></label>
      <label>Destination<select value={p.destination} onChange={(e) => update({ destination: e.target.value as HumanProposal['destination'] })}>{['original_source', 'adapted_copy', 'instructor_supplement', 'student_supplement'].map((v) => <option key={v} value={v}>{label(v)}</option>)}</select></label><label>Priority<select value={p.priority} onChange={(e) => update({ priority: e.target.value as HumanProposal['priority'] })}>{['high', 'medium', 'low'].map((v) => <option key={v}>{v}</option>)}</select></label>
    </fieldset>; })}</fieldset>;
}
