import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { ideaAPI, Capabilities, Estimate, Run, Framework } from '../../../api/idea';
import { taskHelp, AI_DRAFT_NOTE } from './framework-help';
import type { IdeaSavedRecord, IdeaSupport, RevisionProposal, IdeaReview } from '../../../types/idea';
import { CrosswalkDraft } from './CrosswalkDraft';
const taskLabels: Record<string, string> = { '7.1': 'Illustration descriptions', '7.2': 'Example names', '7.3': 'Gender-inclusive language', '7.4': 'Authors, researchers and studies', '7.5': 'Examples and scenarios', '7.6': 'Terminology', '7.7': 'Keywords and metadata', '7.7.1': 'Opening concepts and end summaries', '7.8': 'Missing perspectives and strengths' };
export function RunControls({ api, record, capabilities, framework, flush, report, evidence, addProposal, onDisposition }: { api: ReturnType<typeof ideaAPI>; record: IdeaSavedRecord; capabilities: Capabilities; framework: Framework; flush: () => Promise<IdeaSavedRecord>; report: (e: unknown) => void; evidence: (s: IdeaSupport) => void; addProposal: (p: RevisionProposal, id: string) => void; onDisposition?: (id: string, value: 'useful' | 'needs_correction' | 'rejected') => void }) {
  const synthesis = record.head.kind === 'synthesis';
  const [mode, setMode] = useState(synthesis ? 'synthesis' : 'rubric'), [focus, setFocus] = useState('7.8'), [estimate, setEstimate] = useState<Estimate | null>(null), [ack, setAck] = useState(false), [busy, setBusy] = useState(false), [id, setID] = useState<string | null>(null), [feedback, setFeedback] = useState('useful'), [note, setNote] = useState(''), [before, setBefore] = useState<string | null>(null);
  const history = useQuery({ queryKey: ['idea-runs', api.projectID, record.head._id, before], queryFn: () => api.get<{ items: { _id: string; mode: string; status: string; createdAt: string }[]; nextCursor: string | null }>(`/runs?headID=${record.head._id}&kind=${record.head.kind}${before ? `&before=${encodeURIComponent(before)}` : ''}`), retry: false, cacheTime: 0 });
  const run = useQuery({ queryKey: ['idea-run', api.projectID, id], queryFn: () => api.run(id!), enabled: !!id, retry: false, cacheTime: 0, refetchInterval: (data) => data && ['succeeded', 'failed', 'canceled'].includes(data.status) ? false : 1500 });
  const writable = Boolean(record.capabilities?.write && !record.head.archived && record.revision.data.status === 'draft' && capabilities.write);
  const action = async (fn: () => Promise<void>) => { setBusy(true); try { await fn(); } catch (e) { report(e); } finally { setBusy(false); } };
  const changeMode = (v: string) => { setMode(v); setEstimate(null); setAck(false); };
  return <section><h2>AI Crosswalk drafts</h2><p>Model: {capabilities.profile.primary.model}, high reasoning.</p>
    <p>{capabilities.disclosure.text}</p><p>{capabilities.disclosure.cost}</p>
    {capabilities.remainingQuota?.map((q) => <p key={q.scope}>{q.scope}: {q.remainingRuns} runs and ${(q.remainingMicroUSD / 1e6).toFixed(2)} Luna allowance remaining today.</p>)}
    {!capabilities.aiEnabled && <p>AI is unavailable. You can continue your faculty assessment.</p>}
    {!synthesis && <label>Crosswalk task<select value={mode} onChange={(e) => changeMode(e.target.value)}><option value="rubric">Full ten-row rubric draft</option>{(record.revision.data as IdeaReview).context.focus.flatMap((c) => [c, ...(c === '7.7' ? ['7.7.1'] : [])]).map((c) => <option key={c} value={c}>{c} · {taskLabels[c]}</option>)}<option value="followup">Follow-up on selected draft</option></select></label>}
    {!synthesis && mode === 'followup' && <label>Follow-up focus<select value={focus} onChange={(e) => { setFocus(e.target.value); setEstimate(null); }}>{(record.revision.data as IdeaReview).context.focus.flatMap((c) => [c, ...(c === '7.7' ? ['7.7.1'] : [])]).map((c) => <option key={c} value={c}>{c} · {taskLabels[c]}</option>)}</select></label>}
    {(() => { const help = taskHelp(framework, mode); return help && <details className="idea-help" open><summary>What is this task asking? — {help.heading}</summary><p>{help.summary}</p><p>{AI_DRAFT_NOTE}</p>
      {help.categories.map((c) => <section key={c.id}><h4>{c.id} {c.title}</h4><p>{c.restorative}</p>
        {c.elements.length > 0 && <><p><strong>Elements for consideration</strong></p><ul>{c.elements.map((e) => <li key={e.id}>{e.text}</li>)}</ul></>}
        <p><strong>Rubric rows the draft addresses</strong></p><dl>{c.rows.map((row) => <div key={row.id}><dt>{row.id}</dt><dd><em>Inclusive:</em> {row.inclusive} <em>Emerging:</em> {row.emerging} <em>Exclusive:</em> {row.exclusive}</dd></div>)}</dl></section>)}
      <p className="idea-attribution">Category text: {framework.attribution.title}, {framework.attribution.author}, <a href={framework.attribution.license.url} target="_blank" rel="noreferrer">{framework.attribution.license.name}</a>.</p></details>; })()}
    <button disabled={!writable || !capabilities.aiEnabled || busy || (mode === 'followup' && run.data?.status !== 'succeeded')} onClick={() => action(async () => { const current = await flush(); setAck(false); setEstimate(await api.post<Estimate>('/runs/estimate', { headID: current.head._id, revisionID: current.revision._id, mode, ...(mode === 'followup' ? { parentRunID: id, focus } : {}) })); })}>Save and estimate AI draft</button>
    {estimate && <section><h3>Review this submission</h3><p>Luna reservation: ${(estimate.budget.reservationMicroUSD / 1e6).toFixed(6)}. Expires {new Date(estimate.expiresAt).toLocaleTimeString()}. {estimate.manifest.inputBytes.toLocaleString()} input bytes.</p><p>Captured pages: {estimate.manifest.sources.flatMap((s) => s.pageIDs).join(', ')}. Excluded: {estimate.manifest.sources.flatMap((s) => s.excludedPageIDs).join(', ') || 'none'}.</p><label className="idea-check"><input type="checkbox" checked={ack} onChange={(e) => setAck(e.target.checked)} />I agree to send the disclosed saved content to OpenAI and will review the draft.</label><button disabled={!ack || busy || !writable} onClick={() => action(async () => { await flush(); const result = await api.post<{ runID: string }>('/runs', { estimateID: estimate.estimateID, inputHash: estimate.inputHash, disclosureVersion: estimate.disclosure.version, acknowledgeDataUse: true, idempotencyKey: crypto.randomUUID() }); setID(result.runID); setEstimate(null); await history.refetch(); })}>Request draft</button></section>}
    <h3>Saved runs</h3>{history.isError && <button onClick={() => history.refetch()}>Retry run history</button>}<ul>{history.data?.items.map((r) => <li key={r._id}><button onClick={() => { setID(r._id); setEstimate(null); }}>{r.mode} · {r.status} · {new Date(r.createdAt).toLocaleString()}</button></li>)}</ul>{history.data?.nextCursor && <button onClick={() => setBefore(history.data!.nextCursor)}>Older runs</button>}{before && <button onClick={() => setBefore(null)}>Newest runs</button>}
    {run.isError && <button onClick={() => run.refetch()}>Retry run status</button>}{run.data && <><p role="status">Run {run.data.status} · {run.data.phase}{run.data.cancelRequested ? ' · cancellation requested' : ''}</p>{run.data.error && <p role="alert">{run.data.error.code}. A new request creates a new run; uncertain provider usage is not refunded.</p>}
      {!['succeeded', 'failed', 'canceled'].includes(run.data.status) && record.head.ownerUUID === run.data.ownerUUID && writable && <button disabled={busy} onClick={() => action(async () => { await api.post(`/runs/${id}/cancel`, {}); await run.refetch(); })}>Cancel run</button>}
      <ul>{run.data.attempts?.map((a, i) => <li key={i}>{a.provider}: {a.actualModel ?? 'outcome unavailable'} {a.fallbackReason ? `· fallback: ${a.fallbackReason}` : ''} {a.usage ? `· input ${a.usage.inputTokens ?? 'unknown'}, completion ${a.usage.outputTokens ?? 'unknown'}` : ''}</li>)}</ul>
      {run.data.output && <><p>Generated from saved revision {run.data.revisionIDs.join(', ')}. Current revision: {record.revision._id}.</p><CrosswalkDraft draft={run.data.output} evidence={evidence} addProposal={writable ? (p) => addProposal(p, id!) : undefined} />
        {record.capabilities?.write && <fieldset disabled={busy || (synthesis && !writable)}><legend>Faculty feedback on this AI draft</legend><p>Saved feedback: {run.data.feedback?.disposition ?? 'not reviewed'} {run.data.feedback?.note}</p><label>Disposition<select value={feedback} onChange={(e) => setFeedback(e.target.value)}>{['useful', 'needs_correction', 'rejected'].map((v) => <option key={v}>{v}</option>)}</select></label><label>Feedback note<textarea value={note} maxLength={4000} onChange={(e) => setNote(e.target.value)} /></label><button onClick={() => action(async () => { await api.post(`/runs/${id}/feedback`, { expectedVersion: run.data!.feedback?.version ?? 0, disposition: feedback, note }); await run.refetch(); if (writable) onDisposition?.(id!, feedback as 'useful' | 'needs_correction' | 'rejected'); })}>{synthesis ? 'Save feedback and synthesis disposition' : 'Save draft feedback'}</button></fieldset>}
      </>}
    </>}
  </section>;
}
